apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocdproject5-app
  labels:
    app: argocdproject5-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argocdproject5-app
  template:
    metadata:
      labels:
        app: argocdproject5-app
    spec:
      containers:
        - name: argocdproject5-app
          image: devopsacrdheepika.azurecr.io/nodejs-shopping-cart:latest
          ports:
            - containerPort: 3000
